import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import Web3ModalProvider from "./context/Web3Modal";
import { cookieToInitialState } from "wagmi";
import { headers } from "next/headers";
import { wagmiConfig } from "~/config/wagmi";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const initialState = cookieToInitialState(
    wagmiConfig,
    headers().get("cookie"),
  );
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <Web3ModalProvider initialState={initialState}>
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </Web3ModalProvider>
      </body>
    </html>
  );
}
